language: node_js

os:
  - linux

before_script:
  - git config --global user.email "anonymous@anon.com"
  - git config --global user.name "anonymous"

script:
  - ./pretest.sh
  - nyc npm test && nyc report --reporter=text-lcov | coveralls

node_js:
  - "8"
  - "12"
