language: node_js

os:
  - linux

before_script:
  - git config --global user.email "anonymous@anon.com"
  - git config --global user.name "anonymous"

script:
  - ./pretest.sh
  - NODE_ENV=test YOURPACKAGE_COVERAGE=1 ./node_modules/.bin/mocha ./spec/*.spec.js \
    --require blanket \
    --reporter mocha-lcov-reporter | ./node_modules/coveralls/bin/coveralls.js

node_js:
  - "4"
  - "6"
